services:
  gitlab:
    image: gitlab/gitlab-ce:13.2.8-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.example.com'
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      NO_PROXY: ${NO_PROXY}
      no_proxy: ${no_proxy}
    ports:
      - '80:80'
      - '443:443'
      - '2223:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - '$GITLAB_HOME/gitlab-runner/config:/etc/gitlab-runner'
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITLAB_RUNNER_DISABLE_HELP=1
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${no_proxy}
    depends_on:
      - gitlab
    networks:
      - gitlab-network

  harbor:
    image: registry:2.8
    container_name: harbor
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - '$GITLAB_HOME/harbor/data:/var/lib/registry'
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${no_proxy}
    networks:
      - gitlab-network

  harbor-ui:
    image: hyper/docker-registry-web:latest
    container_name: harbor-ui
    restart: always
    ports:
      - '8080:5000'
    environment:
      - REGISTRY_URL=http://harbor:5000
      - REGISTRY_NAME=Docker Registry
      - REGISTRY_READONLY=false
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${no_proxy}
    networks:
      - gitlab-network
    depends_on:
      - harbor

networks:
  gitlab-network:
    driver: bridge
